version: '3.8'

secrets:
  db_password:
    file: /data/ecosystem/secrets/dev_db_pass
  redis_password:
    file: /data/ecosystem/secrets/dev_redis_pass

services:
  frontend-dev:
    image: frontend-dev:local2
    build:
      context: /data/ecosystem/apps/frontend
      dockerfile: Dockerfile
    networks:
      - swarm_web
      - swarm_development
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: on-failure
    labels:
      - traefik.enable=true
      - traefik.docker.network=swarm_web
      - traefik.http.routers.frontend-dev.rule=Host(`dev.tsbi.fun`)
      - traefik.http.routers.frontend-dev.entrypoints=websecure
      - traefik.http.routers.frontend-dev.tls.certresolver=letsencrypt
      - traefik.http.services.frontend-dev.loadbalancer.server.port=8080

  backend-dev:
    image: backend-dev:local
    build:
      context: /data/ecosystem/apps/backend
      dockerfile: Dockerfile
    networks:
      - swarm_web
      - swarm_development
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://dev@db-dev:5432/devdb
      - DATABASE_PASSWORD_FILE=/run/secrets/db_password
      - REDIS_URL=redis://redis-dev:6379
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    secrets:
      - db_password
      - redis_password
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    labels:
      - traefik.enable=true
      - traefik.docker.network=swarm_web
      - traefik.http.routers.backend-dev.rule=Host(`api-dev.tsbi.fun`)
      - traefik.http.routers.backend-dev.entrypoints=websecure
      - traefik.http.routers.backend-dev.tls.certresolver=letsencrypt
      - traefik.http.services.backend-dev.loadbalancer.server.port=3000
      # API Proxy for frontend
      - traefik.http.routers.api-proxy-dev.rule=Host(`dev.tsbi.fun`) && PathPrefix(`/api`)
      - traefik.http.routers.api-proxy-dev.entrypoints=websecure
      - traefik.http.routers.api-proxy-dev.tls.certresolver=letsencrypt
      - traefik.http.routers.api-proxy-dev.service=backend-dev
      - traefik.http.middlewares.api-proxy-strip.stripprefix.prefixes=/api
      - traefik.http.routers.api-proxy-dev.middlewares=api-proxy-strip
      - traefik.http.routers.api-proxy-dev.priority=100

  db-dev:
    image: postgres:15-alpine
    networks:
      - swarm_development
    environment:
      POSTGRES_USER: dev
      POSTGRES_DB: devdb
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d devdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.75'
          memory: 1G

  redis-dev:
    image: redis:7-alpine
    command:
      - redis-server
      - --appendonly
      - yes
      - --requirepass
      - devredis
    networks:
      - swarm_development
    volumes:
      - dev-redis-data:/data
    secrets:
      - redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "devredis", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

networks:
  swarm_web:
    external: true
  swarm_development:
    external: true

volumes:
  dev-db-data:
  dev-redis-data:
