version: '3.8'

secrets:
  db_password:
    file: /data/ecosystem/secrets/prod_db_pass
  redis_password:
    file: /data/ecosystem/secrets/prod_redis_pass

services:
  frontend-prod:
    image: frontend-prod:local
    build:
      context: /data/ecosystem/apps/frontend
      dockerfile: Dockerfile
    networks:
      - swarm_web
      - swarm_production
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: on-failure
    labels:
      - traefik.enable=true
      - traefik.docker.network=swarm_web
      - traefik.http.routers.frontend-prod.rule=Host(`tsbi.fun`) || Host(`www.tsbi.fun`)
      - traefik.http.routers.frontend-prod.entrypoints=websecure
      - traefik.http.routers.frontend-prod.tls.certresolver=letsencrypt
      - traefik.http.services.frontend-prod.loadbalancer.server.port=80

  backend-prod:
    image: backend-prod:local
    build:
      context: /data/ecosystem/apps/backend
      dockerfile: Dockerfile
    networks:
      - swarm_web
      - swarm_production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://prod@db-prod:5432/proddb
      - DATABASE_PASSWORD_FILE=/run/secrets/db_password
      - REDIS_URL=redis://redis-prod:6379
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    secrets:
      - db_password
      - redis_password
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    labels:
      - traefik.enable=true
      - traefik.docker.network=swarm_web
      - traefik.http.routers.backend-prod.rule=Host(`api.tsbi.fun`)
      - traefik.http.routers.backend-prod.entrypoints=websecure
      - traefik.http.routers.backend-prod.tls.certresolver=letsencrypt
      - traefik.http.services.backend-prod.loadbalancer.server.port=3000
      # API Proxy for frontend
      - traefik.http.routers.api-proxy-prod.rule=(Host(`tsbi.fun`) || Host(`www.tsbi.fun`)) && PathPrefix(`/api`)
      - traefik.http.routers.api-proxy-prod.entrypoints=websecure
      - traefik.http.routers.api-proxy-prod.tls.certresolver=letsencrypt
      - traefik.http.routers.api-proxy-prod.service=backend-prod
      - traefik.http.middlewares.api-proxy-prod.stripprefix.prefixes=/api
      - traefik.http.routers.api-proxy-prod.middlewares=api-proxy-prod
      - traefik.http.routers.api-proxy-prod.priority=100

  db-prod:
    image: postgres:15-alpine
    networks:
      - swarm_production
    environment:
      POSTGRES_USER: prod
      POSTGRES_DB: proddb
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - prod-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prod -d proddb"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.75'
          memory: 1G

  redis-prod:
    image: redis:7-alpine
    command:
      - redis-server
      - --appendonly
      - yes
      - --requirepass
      - prodredis
    networks:
      - swarm_production
    volumes:
      - prod-redis-data:/data
    secrets:
      - redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "prodredis", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

networks:
  swarm_web:
    external: true
  swarm_production:
    external: true

volumes:
  prod-db-data:
  prod-redis-data: